services:
  flask_app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - redis_db
    networks:
      - app-network

  redis_db:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
volumes:
  redis_data:
